apiVersion: v1
kind: ServiceAccount
metadata:
  name: vault
  namespace: vault

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: vault-secret-access
  namespace: vault
rules:
  - apiGroups:
      - ''
    resources:
      - secrets
      - configmaps
    verbs:
      - get
      - create
      - update
      - patch

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: vault-secret-access-binding
  namespace: vault
subjects:
  - kind: ServiceAccount
    name: vault
    namespace: vault
roleRef:
  kind: Role
  name: vault-secret-access
  apiGroup: rbac.authorization.k8s.io
